### ISSUE TITLE
Integration Architecture Document: Fix Platform Capabilities diagram

### ISSUE THREAD

**Issue by focadiz** [RideXpress/docs#28]
https://github.com/RideXpress/docs/blob/main/architecture/integration-arquitecture-document.md#table-of-main-integration-use-cases

The diagram is not clear, doesn't have a good resolution

**Comment by JuanCBasso** [comment]
Close this issue when https://github.com/RideXpress/docs/pull/69 is merged.

**Comment by JuanCBasso** [comment]
Fixed in PR #69
