### ISSUE TITLE
Investigate if the Knowledge Hub has a template for Integration Design

### ISSUE THREAD

**Issue by focadiz** [RideXpress/docs#81]
Sometime ago Paola submitted the TDD template to document our Integrations but it would be nice to know if there is a template in the Knowledge Hub to review and check if there are items we may pull from there to incorporate into our own template.

**Comment by JuanCBasso** [comment]
I found in the Knowledge hub the following documents that could help us in that way:
- https://knowledgehub.mulesoft.com/s/article/API-Design-Document
- https://knowledgehub.mulesoft.com/s/article/Solution-Design-Template
We can review them in detail in the next meeting.

**Comment by focadiz** [comment]
Thanks for sharing @JuanCBasso, closing issue.
